### PR TITLE
simplify structure of company data return by the API.

### PR DESCRIPTION
**Pull request by leonarf**
Removes 2 layers of array that are not really useful.

### CODE REVIEW

**Review by phe-sto — COMMENTED** [review]
I have to admit I doubted a lot about the structure. I thought about this one and even developed it because but changed my mind because I thought it would be more complex for frontend developer to parse the JSON if they don't know which year/bundle is present.
If they request specific year the endpoint is also present, for instance `http://api.enthic.fr/company/siren/330956871/2018` if remove on layer.
The same logic apply for bundle layer, you don't know which one will be present.
Won't you think it is harder to parse?
Is there any standard for those kind of structure?

**Comment by leonarf** [comment]
As the first front-end developper to use the API, I don't find any difficulties to have a list of JSON properties instead of an array in the structure, because properties can be parsed the same way an array does, but it's easier with properties to test the existence of a particular value, and get it straight away. And cherry on top of the cake : it reduce size of data overall, because property name carries data, instead of array position, which don't carry useful data.

**Comment by leonarf** [comment]
I rebased the PR to master, and added a new commit to add APE code as number to the data returned by the API. So data contains APE code as number and as description.

**Comment by leonarf** [comment]
This Pull request fix the issue #21

**Comment by leonarf** [comment]
I close this Pull Request because I included it's content into the PR #27

**Pull request closed without merging**
